name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Init project for Capacitor
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli
          mkdir -p dist
          echo "<!doctype html><html><head><meta charset='utf-8'></head><body>Radni Sati</body></html>" > dist/index.html
          cat > capacitor.config.ts <<'EOF'
          import { CapacitorConfig } from '@capacitor/cli';
          const config: CapacitorConfig = {
            appId: 'com.maa.radnisati',
            appName: 'Radni Sati',
            webDir: 'dist',
            server: {
              url: 'https://abedinmujezinovic0-prog.github.io/RADNI-SATI/',
              cleartext: false,
              androidScheme: 'https'
            }
          };
          export default config;
          EOF

      - name: Add Android platform
        run: npx cap add android

      - name: Build APK (debug)
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: RadniSati-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
